# Generated by Django 5.1 on 2024-09-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextra", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default="noreply@example.com", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="f_name",
            field=models.CharField(default="First name", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="l_name",
            field=models.CharField(default="Last name", max_length=50),
        ),
    ]
