# Generated by Django 5.1 on 2024-09-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codextra", "0003_remove_user_id_alter_user_user"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
