# Generated by Django 5.1 on 2024-09-14 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("codextra", "0004_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("f_name", models.CharField(default="First name", max_length=50)),
                ("l_name", models.CharField(default="Last name", max_length=50)),
                (
                    "email",
                    models.EmailField(default="noreply@example.com", max_length=100),
                ),
            ],
        ),
    ]
