# Generated by Django 5.1 on 2024-09-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codextra", "0005_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
