# Generated by Django 5.1 on 2024-09-14 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextra", "0007_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="codextra.user",
                    ),
                ),
                ("bank_account", models.CharField(max_length=20)),
                ("routing_no", models.CharField(max_length=20)),
            ],
            bases=("codextra.user",),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="codextra.user",
                    ),
                ),
                ("level", models.CharField(max_length=50)),
            ],
            bases=("codextra.user",),
        ),
    ]
