# Generated by Django 5.1 on 2024-09-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextra", "0008_instructor_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor", name="bank_account", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="instructor", name="routing_no", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="student", name="level", field=models.IntegerField(default=0),
        ),
    ]
