# Generated by Django 5.1 on 2024-09-14 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextra", "0012_digital_wallet_enroll_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="course_material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_no", models.IntegerField(default=1)),
                ("section_name", models.CharField(max_length=100)),
                (
                    "m_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("video", "Video")],
                        default="pdf",
                        max_length=5,
                    ),
                ),
                ("m_title", models.CharField(max_length=100)),
                ("file_loc", models.FileField(upload_to="videos/")),
                ("duration", models.FloatField()),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codextra.course",
                    ),
                ),
            ],
            options={"unique_together": {("course_id", "section_no", "m_title")},},
        ),
    ]
