# Generated by Django 5.1 on 2024-09-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextra", "0013_course_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_material",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course_material",
            name="file_loc",
            field=models.FileField(upload_to="media/"),
        ),
    ]
