# Generated by Django 5.1 on 2024-09-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextra", "0016_alter_course_material_file_loc"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="course_material", unique_together=set(),),
        migrations.AddConstraint(
            model_name="course_material",
            constraint=models.UniqueConstraint(
                fields=("course_id", "section_no", "m_title"),
                name="unique_course_material",
            ),
        ),
    ]
