# Generated by Django 5.1 on 2024-09-17 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextra", "0018_alter_course_material_file_loc"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_no", models.IntegerField()),
                ("section_name", models.CharField(max_length=100)),
                (
                    "m_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("video", "Video")],
                        default="pdf",
                        max_length=5,
                    ),
                ),
                ("m_title", models.CharField(max_length=100)),
                ("file_loc", models.FileField(upload_to="")),
                ("duration", models.FloatField(blank=True, null=True)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codextra.course",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="course_material",),
        migrations.AddConstraint(
            model_name="coursematerial",
            constraint=models.UniqueConstraint(
                fields=("course_id", "section_no", "m_title"),
                name="unique_course_material",
            ),
        ),
    ]
